Unit.create(name: 'litro', acronym: 'l')
Unit.create(name: 'mililitro', acronym: 'ml')
Unit.create(name: 'xícara de café', acronym: 'xíc. café')
Unit.create(name: 'xícara de chá', acronym: 'xíc. chá')
Unit.create(name: 'colher de sopa', acronym: 'col. sopa')
Unit.create(name: 'colher de café', acronym: 'col. café')
Unit.create(name: 'colher de chá', acronym: 'col. chá')
Unit.create(name: 'copo americano', acronym: 'cop. americano')
Unit.create(name: 'unidade', acronym: 'un')
